"""
Hand-curated ACLED-style event catalog for oil supply disruptions.
20 real events, each tagged with: node, channel, severity, restored,
actor/event-type, geocode, source triangulation metadata.

This dataset does triple duty:
  (a) few-shot seeds for the classifier keyword matcher
  (b) honest audit trail shown in the UI
  (c) join key to backtest each event against EIA price reaction
"""

from typing import Dict, List, Optional

DISRUPTION_EVENTS: List[Dict] = [
    {
        "event_id": "abqaiq_2019",
        "title": "Abqaiq / Khurais drone & cruise-missile attack (Saudi Aramco)",
        "date": "2019-09-14",
        "node_id": "ghawar_abqaiq",
        "channel": "production",
        "region": "Middle East / Saudi Arabia",
        "severity": "sustained",
        "restored": False,
        "actor_event_type": "drone attack / infrastructure sabotage",
        "location": "Abqaiq & Khurais, Saudi Arabia",
        "lat": 25.94, "lon": 49.67,
        "n_sources": 8,
        "source_scale": "international",
        "precision": "exact_site",
        "notes": "~5.7 Mb/d (~50% Saudi capacity) taken offline. Partly restored ~Sep 25 but classic production shock.",
    },
    {
        "event_id": "gulf_oman_2019",
        "title": "Gulf of Oman tanker attacks (limpet mines)",
        "date": "2019-06-13",
        "node_id": "hormuz",
        "channel": "transport",
        "region": "Middle East",
        "severity": "scare",
        "restored": False,
        "actor_event_type": "tanker attack",
        "location": "Gulf of Oman",
        "lat": 24.5, "lon": 58.5,
        "n_sources": 5,
        "source_scale": "international",
        "precision": "regional",
        "notes": "Limpet mine attacks on Kokuka Courageous + Front Altair. Short-lived spike.",
    },
    {
        "event_id": "suez_2021",
        "title": "Ever Given Suez Canal grounding",
        "date": "2021-03-23",
        "node_id": "suez",
        "channel": "transport",
        "region": "North Africa / Mediterranean",
        "severity": "outage",
        "restored": True,
        "actor_event_type": "accident / blockade",
        "location": "Suez Canal, Egypt",
        "lat": 30.5, "lon": 32.3,
        "n_sources": 12,
        "source_scale": "international",
        "precision": "exact_site",
        "notes": "6-day full blockage. Crude reaction muted vs macro backdrop (COVID recovery rally).",
    },
    {
        "event_id": "houthi_red_sea_2023",
        "title": "Houthi Red Sea campaign (ongoing from Dec 2023)",
        "date": "2023-12-15",
        "node_id": "bab_el_mandeb",
        "channel": "transport",
        "region": "Red Sea / Horn of Africa",
        "severity": "sustained",
        "restored": False,
        "actor_event_type": "missile / drone attack on commercial shipping",
        "location": "Red Sea / Bab-el-Mandeb",
        "lat": 12.6, "lon": 43.4,
        "n_sources": 10,
        "source_scale": "international",
        "precision": "regional",
        "notes": "Sustained Houthi attacks rerouted ~50 tankers/week around Cape of Good Hope (+15 days).",
    },
    {
        "event_id": "russia_invasion_2022",
        "title": "Russia invasion of Ukraine + G7 oil sanctions",
        "date": "2022-02-24",
        "node_id": "russia_siberia",
        "channel": "production",
        "region": "Russia / FSU",
        "severity": "sustained",
        "restored": False,
        "actor_event_type": "geopolitical conflict / sanction",
        "location": "Russia / Ukraine (broad)",
        "lat": 60.0, "lon": 60.0,
        "n_sources": 20,
        "source_scale": "international",
        "precision": "national",
        "notes": "~1-2 Mb/d effectively removed via G7 oil price cap + sanctions. Diesel crack blew to +$50/bbl peak.",
    },
    {
        "event_id": "forties_2017",
        "title": "Forties Pipeline System crack — shutdown",
        "date": "2017-12-11",
        "node_id": "north_sea",
        "channel": "transport",
        "region": "Northwest Europe",
        "severity": "outage",
        "restored": True,
        "actor_event_type": "infrastructure failure (crack in pipeline)",
        "location": "Forties Pipeline, North Sea / NE Scotland",
        "lat": 57.5, "lon": -1.5,
        "n_sources": 6,
        "source_scale": "national",
        "precision": "exact_site",
        "notes": "Key Brent basket grade (Forties). Pipeline crack → Brent +5% vs WTI +2%; arb widened.",
    },
    {
        "event_id": "uri_2021",
        "title": "Winter Storm Uri — Texas/Permian production freeze",
        "date": "2021-02-15",
        "node_id": "permian",
        "channel": "production",
        "region": "US / Midcontinent",
        "severity": "outage",
        "restored": True,
        "actor_event_type": "natural disaster / extreme cold snap",
        "location": "Permian Basin / Texas",
        "lat": 32.0, "lon": -101.5,
        "n_sources": 8,
        "source_scale": "national",
        "precision": "regional",
        "notes": "~4 Mb/d briefly shut-in. WTI-led; Brent-WTI arb narrowed.",
    },
    {
        "event_id": "harvey_2017",
        "title": "Hurricane Harvey — USGC refinery disruption",
        "date": "2017-08-25",
        "node_id": "usgc_padd3",
        "channel": "production",
        "region": "USGC / Atlantic Basin",
        "severity": "sustained",
        "restored": True,
        "actor_event_type": "hurricane / natural disaster",
        "location": "US Gulf Coast (Houston–Beaumont–Port Arthur)",
        "lat": 29.7, "lon": -95.4,
        "n_sources": 12,
        "source_scale": "national",
        "precision": "regional",
        "notes": "~5 Mb/d refinery capacity down. WTI FELL (less crude demand); gasoline crack SURGED. Classic refinery sign-flip.",
    },
    {
        "event_id": "french_strikes_2022",
        "title": "French TotalEnergies refinery strikes",
        "date": "2022-10-10",
        "node_id": "rotterdam_ara",
        "channel": "production",
        "region": "Northwest Europe / Atlantic",
        "severity": "sustained",
        "restored": True,
        "actor_event_type": "labor strike / industrial action",
        "location": "France (Normandie, Donges, La Mède refineries)",
        "lat": 49.4, "lon": 0.2,
        "n_sources": 5,
        "source_scale": "national",
        "precision": "regional",
        "notes": "Fuel queue panic at French petrol stations. Crude demand softer; European products tightened.",
    },
    {
        "event_id": "katrina_2005",
        "title": "Hurricane Katrina — USGC infrastructure strike",
        "date": "2005-08-29",
        "node_id": "usgc_padd3",
        "channel": "production",
        "region": "USGC / Atlantic Basin",
        "severity": "sustained",
        "restored": True,
        "actor_event_type": "hurricane / natural disaster",
        "location": "New Orleans / Louisiana Gulf Coast",
        "lat": 29.95, "lon": -90.07,
        "n_sources": 15,
        "source_scale": "national",
        "precision": "regional",
        "notes": "~1.5 Mb/d production + refinery disrupted. Gasoline crack spiked ~$1/gal.",
    },
    {
        "event_id": "colonial_2021",
        "title": "Colonial Pipeline ransomware shutdown",
        "date": "2021-05-07",
        "node_id": "usgc_padd3",
        "channel": "transport",
        "region": "USGC / Atlantic Basin",
        "severity": "outage",
        "restored": True,
        "actor_event_type": "cyberattack / ransomware",
        "location": "Colonial Pipeline (USGC to US East Coast)",
        "lat": 32.5, "lon": -86.0,
        "n_sources": 10,
        "source_scale": "national",
        "precision": "national",
        "notes": "Product pipeline (not refinery) hit. Gasoline crack elevated; crude less affected. Transport channel.",
    },
    {
        "event_id": "iran_sanctions_2018",
        "title": "US reimposed Iran nuclear sanctions (JCPOA exit)",
        "date": "2018-05-08",
        "node_id": "hormuz",
        "channel": "production",
        "region": "Middle East",
        "severity": "sustained",
        "restored": False,
        "actor_event_type": "sanction / geopolitical",
        "location": "Iran (broad) / Persian Gulf supply route",
        "lat": 32.0, "lon": 53.0,
        "n_sources": 12,
        "source_scale": "international",
        "precision": "national",
        "notes": "~1 Mb/d Iranian exports removed. Brent > WTI reaction (seaborne grade tightened).",
    },
    {
        "event_id": "saudi_cuts_2023",
        "title": "Saudi voluntary unilateral production cut (OPEC+)",
        "date": "2023-04-02",
        "node_id": "ghawar_abqaiq",
        "channel": "production",
        "region": "Middle East / Saudi Arabia",
        "severity": "sustained",
        "restored": False,
        "actor_event_type": "OPEC production decision",
        "location": "Saudi Arabia",
        "lat": 24.0, "lon": 45.0,
        "n_sources": 10,
        "source_scale": "international",
        "precision": "national",
        "notes": "1 Mb/d unilateral Saudi cut. Brent +8% over T+5 window.",
    },
    {
        "event_id": "bosphorus_delays_2022",
        "title": "Bosphorus tanker delays (insurance / Russia sanctions)",
        "date": "2022-12-05",
        "node_id": "bosphorus",
        "channel": "transport",
        "region": "Black Sea / Turkey",
        "severity": "sustained",
        "restored": True,
        "actor_event_type": "regulatory / insurance / sanction-driven delay",
        "location": "Turkish Straits (Bosphorus)",
        "lat": 41.1, "lon": 29.0,
        "n_sources": 6,
        "source_scale": "international",
        "precision": "regional",
        "notes": "Insurance requirement disputes queued ~20-30 tankers. G7 price-cap implementation date.",
    },
    {
        "event_id": "opec_cuts_2016",
        "title": "OPEC Vienna production-cut agreement",
        "date": "2016-11-30",
        "node_id": "ghawar_abqaiq",
        "channel": "production",
        "region": "Middle East / Saudi Arabia",
        "severity": "sustained",
        "restored": False,
        "actor_event_type": "OPEC production decision",
        "location": "Vienna / Saudi Arabia (supply removal)",
        "lat": 24.0, "lon": 45.0,
        "n_sources": 12,
        "source_scale": "international",
        "precision": "national",
        "notes": "First OPEC deal since 2008. WTI +8% T+0.",
    },
    {
        "event_id": "kashagan_2013",
        "title": "Kashagan oilfield H2S pipeline leak — multi-year shutdown",
        "date": "2013-10-03",
        "node_id": "russia_siberia",
        "channel": "production",
        "region": "Russia / FSU",
        "severity": "sustained",
        "restored": True,
        "actor_event_type": "equipment failure (H2S corrosion in pipeline)",
        "location": "Kashagan, Kazakhstan (Caspian Sea)",
        "lat": 45.4, "lon": 52.3,
        "n_sources": 5,
        "source_scale": "national",
        "precision": "exact_site",
        "notes": "Major Caspian field; ~1-2 years full repair. Brent muted (~+2%); FSU-node analog.",
    },
    {
        "event_id": "north_sea_elgin_2012",
        "title": "Elgin gas platform gas leak — production shutdown",
        "date": "2012-03-25",
        "node_id": "north_sea",
        "channel": "production",
        "region": "Northwest Europe",
        "severity": "outage",
        "restored": True,
        "actor_event_type": "gas leak / safety shutdown",
        "location": "Elgin Field, North Sea (offshore UK)",
        "lat": 57.0, "lon": 2.0,
        "n_sources": 4,
        "source_scale": "national",
        "precision": "exact_site",
        "notes": "~36 Kbbl/d. Brent +2% T+0. Small-magnitude North Sea production analog.",
    },
    {
        "event_id": "iran_hormuz_threat_2012",
        "title": "Iran admiral threatens Hormuz closure",
        "date": "2012-01-03",
        "node_id": "hormuz",
        "channel": "transport",
        "region": "Middle East",
        "severity": "scare",
        "restored": False,
        "actor_event_type": "geopolitical threat (unexecuted)",
        "location": "Strait of Hormuz",
        "lat": 26.5, "lon": 56.4,
        "n_sources": 6,
        "source_scale": "international",
        "precision": "regional",
        "notes": "Iran threatened closure in response to US sanctions. WTI +4% T+0; faded within 5 days.",
    },
    {
        "event_id": "hurricane_rita_2005",
        "title": "Hurricane Rita — second USGC strike (weeks after Katrina)",
        "date": "2005-09-24",
        "node_id": "usgc_padd3",
        "channel": "production",
        "region": "USGC / Atlantic Basin",
        "severity": "outage",
        "restored": True,
        "actor_event_type": "hurricane / natural disaster",
        "location": "Texas / Louisiana Gulf Coast",
        "lat": 29.9, "lon": -93.9,
        "n_sources": 8,
        "source_scale": "national",
        "precision": "regional",
        "notes": "~2 Mb/d refinery capacity hit. Muted vs Katrina (market had partly recovered).",
    },
    {
        "event_id": "libya_blockade_2020",
        "title": "Libya National Oil Corp. terminal blockade",
        "date": "2020-01-17",
        "node_id": None,
        "channel": "production",
        "region": "North Africa / Libya",
        "severity": "sustained",
        "restored": True,
        "actor_event_type": "militia blockade / armed conflict",
        "location": "Libya (Es Sider, Ras Lanuf, Al-Sharara terminals)",
        "lat": 30.4, "lon": 18.5,
        "n_sources": 7,
        "source_scale": "international",
        "precision": "regional",
        "notes": "~1.2 Mb/d shut-in. No direct node match (Libya not in 15 nodes). Structural prior → Brent-led.",
    },
]

EVENTS_BY_ID: Dict[str, Dict] = {e["event_id"]: e for e in DISRUPTION_EVENTS}

EVENTS_BY_NODE: Dict[str, List[Dict]] = {}
for _ev in DISRUPTION_EVENTS:
    nid = _ev.get("node_id")
    if nid:
        EVENTS_BY_NODE.setdefault(nid, []).append(_ev)
