"""Initial schema

Revision ID: 7b69d724ed02
Revises: 
Create Date: 2026-06-08 04:09:52.555477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b69d724ed02'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('alert_type', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_alert_type'), 'alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_table('inventory',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('series_id', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('period', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_id'), 'inventory', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_series_id'), 'inventory', ['series_id'], unique=False)
    op.create_index(op.f('ix_inventory_timestamp'), 'inventory', ['timestamp'], unique=False)
    op.create_table('macro_indicators',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('indicator_name', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('change_pct', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_macro_indicators_id'), 'macro_indicators', ['id'], unique=False)
    op.create_index(op.f('ix_macro_indicators_indicator_name'), 'macro_indicators', ['indicator_name'], unique=False)
    op.create_index(op.f('ix_macro_indicators_timestamp'), 'macro_indicators', ['timestamp'], unique=False)
    op.create_table('model_metadata',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('trained_at', sa.DateTime(), nullable=True),
    sa.Column('training_end_date', sa.String(), nullable=True),
    sa.Column('n_training_samples', sa.Integer(), nullable=True),
    sa.Column('n_features', sa.Integer(), nullable=True),
    sa.Column('hyperparameters_json', sa.Text(), nullable=True),
    sa.Column('wf_accuracy', sa.Float(), nullable=True),
    sa.Column('wf_precision_high_conf', sa.Float(), nullable=True),
    sa.Column('wf_sharpe', sa.Float(), nullable=True),
    sa.Column('wf_brier_score', sa.Float(), nullable=True),
    sa.Column('top_features_json', sa.Text(), nullable=True),
    sa.Column('regime_metrics_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_metadata_id'), 'model_metadata', ['id'], unique=False)
    op.create_index(op.f('ix_model_metadata_model_name'), 'model_metadata', ['model_name'], unique=False)
    op.create_table('news',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('headline', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('sentiment_label', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('entities', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_fetched_at'), 'news', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_news_id'), 'news', ['id'], unique=False)
    op.create_index(op.f('ix_news_published_at'), 'news', ['published_at'], unique=False)
    op.create_table('prediction_features',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('features_json', sa.Text(), nullable=True),
    sa.Column('regime_label', sa.String(), nullable=True),
    sa.Column('regime_severity', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_features_date'), 'prediction_features', ['date'], unique=False)
    op.create_index(op.f('ix_prediction_features_id'), 'prediction_features', ['id'], unique=False)
    op.create_index(op.f('ix_prediction_features_symbol'), 'prediction_features', ['symbol'], unique=False)
    op.create_table('prediction_regimes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('regime_label', sa.String(), nullable=True),
    sa.Column('regime_severity', sa.Float(), nullable=True),
    sa.Column('hmm_prob_contango', sa.Float(), nullable=True),
    sa.Column('hmm_prob_backwardation', sa.Float(), nullable=True),
    sa.Column('hmm_prob_neutral', sa.Float(), nullable=True),
    sa.Column('transition_prob_contango', sa.Float(), nullable=True),
    sa.Column('transition_prob_backwardation', sa.Float(), nullable=True),
    sa.Column('transition_prob_neutral', sa.Float(), nullable=True),
    sa.Column('regime_age_days', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_regimes_date'), 'prediction_regimes', ['date'], unique=False)
    op.create_index(op.f('ix_prediction_regimes_id'), 'prediction_regimes', ['id'], unique=False)
    op.create_index(op.f('ix_prediction_regimes_symbol'), 'prediction_regimes', ['symbol'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('horizon_days', sa.Integer(), nullable=True),
    sa.Column('target', sa.String(), nullable=True),
    sa.Column('prediction_value', sa.Float(), nullable=True),
    sa.Column('prediction_label', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('ci_lower', sa.Float(), nullable=True),
    sa.Column('ci_upper', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('actual_value', sa.Float(), nullable=True),
    sa.Column('actual_label', sa.String(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_date'), 'predictions', ['date'], unique=False)
    op.create_index(op.f('ix_predictions_id'), 'predictions', ['id'], unique=False)
    op.create_index(op.f('ix_predictions_symbol'), 'predictions', ['symbol'], unique=False)
    op.create_table('price_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_history_date'), 'price_history', ['date'], unique=False)
    op.create_index(op.f('ix_price_history_id'), 'price_history', ['id'], unique=False)
    op.create_index(op.f('ix_price_history_symbol'), 'price_history', ['symbol'], unique=False)
    op.create_index(op.f('ix_price_history_timestamp'), 'price_history', ['timestamp'], unique=False)
    op.create_table('prices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prices_id'), 'prices', ['id'], unique=False)
    op.create_index(op.f('ix_prices_symbol'), 'prices', ['symbol'], unique=False)
    op.create_index(op.f('ix_prices_timestamp'), 'prices', ['timestamp'], unique=False)
    op.create_table('spreads',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('spread_name', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('avg_5day', sa.Float(), nullable=True),
    sa.Column('avg_30day', sa.Float(), nullable=True),
    sa.Column('deviation_5day', sa.Float(), nullable=True),
    sa.Column('deviation_30day', sa.Float(), nullable=True),
    sa.Column('is_anomaly', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spreads_id'), 'spreads', ['id'], unique=False)
    op.create_index(op.f('ix_spreads_spread_name'), 'spreads', ['spread_name'], unique=False)
    op.create_index(op.f('ix_spreads_timestamp'), 'spreads', ['timestamp'], unique=False)
    op.create_table('trade_recommendations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('conviction', sa.String(), nullable=True),
    sa.Column('instrument', sa.String(), nullable=True),
    sa.Column('entry_low', sa.Float(), nullable=True),
    sa.Column('entry_high', sa.Float(), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('risk_reward_ratio', sa.Float(), nullable=True),
    sa.Column('position_size_pct', sa.Float(), nullable=True),
    sa.Column('max_holding_days', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('explanation_json', sa.Text(), nullable=True),
    sa.Column('regime_label', sa.String(), nullable=True),
    sa.Column('regime_severity', sa.Float(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('exit_date', sa.String(), nullable=True),
    sa.Column('pnl_pct', sa.Float(), nullable=True),
    sa.Column('outcome', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_recommendations_date'), 'trade_recommendations', ['date'], unique=False)
    op.create_index(op.f('ix_trade_recommendations_id'), 'trade_recommendations', ['id'], unique=False)
    op.create_index(op.f('ix_trade_recommendations_symbol'), 'trade_recommendations', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_recommendations_symbol'), table_name='trade_recommendations')
    op.drop_index(op.f('ix_trade_recommendations_id'), table_name='trade_recommendations')
    op.drop_index(op.f('ix_trade_recommendations_date'), table_name='trade_recommendations')
    op.drop_table('trade_recommendations')
    op.drop_index(op.f('ix_spreads_timestamp'), table_name='spreads')
    op.drop_index(op.f('ix_spreads_spread_name'), table_name='spreads')
    op.drop_index(op.f('ix_spreads_id'), table_name='spreads')
    op.drop_table('spreads')
    op.drop_index(op.f('ix_prices_timestamp'), table_name='prices')
    op.drop_index(op.f('ix_prices_symbol'), table_name='prices')
    op.drop_index(op.f('ix_prices_id'), table_name='prices')
    op.drop_table('prices')
    op.drop_index(op.f('ix_price_history_timestamp'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_symbol'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_id'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_date'), table_name='price_history')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_predictions_symbol'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_date'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_prediction_regimes_symbol'), table_name='prediction_regimes')
    op.drop_index(op.f('ix_prediction_regimes_id'), table_name='prediction_regimes')
    op.drop_index(op.f('ix_prediction_regimes_date'), table_name='prediction_regimes')
    op.drop_table('prediction_regimes')
    op.drop_index(op.f('ix_prediction_features_symbol'), table_name='prediction_features')
    op.drop_index(op.f('ix_prediction_features_id'), table_name='prediction_features')
    op.drop_index(op.f('ix_prediction_features_date'), table_name='prediction_features')
    op.drop_table('prediction_features')
    op.drop_index(op.f('ix_news_published_at'), table_name='news')
    op.drop_index(op.f('ix_news_id'), table_name='news')
    op.drop_index(op.f('ix_news_fetched_at'), table_name='news')
    op.drop_table('news')
    op.drop_index(op.f('ix_model_metadata_model_name'), table_name='model_metadata')
    op.drop_index(op.f('ix_model_metadata_id'), table_name='model_metadata')
    op.drop_table('model_metadata')
    op.drop_index(op.f('ix_macro_indicators_timestamp'), table_name='macro_indicators')
    op.drop_index(op.f('ix_macro_indicators_indicator_name'), table_name='macro_indicators')
    op.drop_index(op.f('ix_macro_indicators_id'), table_name='macro_indicators')
    op.drop_table('macro_indicators')
    op.drop_index(op.f('ix_inventory_timestamp'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_series_id'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_id'), table_name='inventory')
    op.drop_table('inventory')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_type'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
