"""RegimeHistory JSON migration Phase 4B

Revision ID: adbe9131f9ef
Revises: 7b69d724ed02
Create Date: 2026-06-08 04:15:44.300951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adbe9131f9ef'
down_revision: Union[str, Sequence[str], None] = '7b69d724ed02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prediction_regimes', sa.Column('probabilities_json', sa.Text(), nullable=True))
    op.add_column('prediction_regimes', sa.Column('transitions_json', sa.Text(), nullable=True))
    op.add_column('prediction_regimes', sa.Column('similar_periods_json', sa.Text(), nullable=True))
    op.drop_column('prediction_regimes', 'hmm_prob_contango')
    op.drop_column('prediction_regimes', 'hmm_prob_backwardation')
    op.drop_column('prediction_regimes', 'transition_prob_neutral')
    op.drop_column('prediction_regimes', 'hmm_prob_neutral')
    op.drop_column('prediction_regimes', 'transition_prob_contango')
    op.drop_column('prediction_regimes', 'transition_prob_backwardation')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prediction_regimes', sa.Column('transition_prob_backwardation', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('prediction_regimes', sa.Column('transition_prob_contango', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('prediction_regimes', sa.Column('hmm_prob_neutral', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('prediction_regimes', sa.Column('transition_prob_neutral', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('prediction_regimes', sa.Column('hmm_prob_backwardation', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('prediction_regimes', sa.Column('hmm_prob_contango', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('prediction_regimes', 'similar_periods_json')
    op.drop_column('prediction_regimes', 'transitions_json')
    op.drop_column('prediction_regimes', 'probabilities_json')
    # ### end Alembic commands ###
